# Generated by Django 3.1.5 on 2021-01-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='unique_id',
        ),
    ]
